image: schickling/rust

stages:
  - build

job:
  stage: build
  script:
    - uname -a
    - DEBIAN_FRONTEND=noninteractive apt-get update -y
    - DEBIAN_FRONTEND=noninteractive apt-get install -y gcc openssl libssl-dev sqlite3 libsqlite3-dev
    - cargo build --release