[package]
name = "clubstatusd"
version = "0.2.2"
authors = ["clonejo <clonejo@shakik.de>"]

[dependencies]
rusqlite = "0.4.0"
chrono = "0.2"
libc = "0.2"
rustc-serialize = "0.3"
clap = "1.*"
config = "~0.1.0"
hyper = "*"
regex = "0.1"
route-recognizer = "0.1"
urlparse = "^0.7"
rumqtt = {git = "https://github.com/Ather-Energy/RuMqtt.git"}
time = "^0.1"
sodiumoxide = "0.0.14"

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
