[package]
name = "clubstatusd"
version = "0.2.0"
authors = ["clonejo <clonejo@shakik.de>"]

[dependencies]
rusqlite = "0.4.0"
chrono = "0.2"
libc = "0.2"
rustc-serialize = "0.3"
clap = "1.*"
config = "~0.1.0"
hyper = "*"
regex = "0.1"
route-recognizer = "0.1"
urlparse = "^0.7"
mqttc = "^0.1.2"
netopt = "^0.1.2"
time = "^0.1"
