[package]
name = "clubstatusd"
version = "0.2.5"
authors = ["clonejo <clonejo@shakik.de>"]

[dependencies]
chrono = "0.4.0"
clap = "2.29.0"
config = "0.7.1"
hyper = "0.10.9"
libc = "0.2"
regex = "1.1.0"
route-recognizer = "0.1"
rumqtt = "0.30.1"
rusqlite = "0.14.0"
rustc-serialize = "0.3"
sodiumoxide = "0.2.0"
time = "^0.1"
urlparse = "^0.7"

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
