[package]
name = "clubstatusd"
version = "0.1.0"
authors = ["clonejo <clonejo@shakik.de>"]

[dependencies]
rusqlite = "0.4.0"
chrono = "0.2"
libc = "0.2"
rustc-serialize = "0.3"

iron = "*"
router = "0.1.0"
