
# What address to listen on, default:
#listen = "localhost:8000"

# Path to sqlite database, default:
#database_path = "/var/local/clubstatusd/db.sqlite"
database_path = "./db.sqlite"

# Restrict the API to clients with the correct password (HTTP Basic Auth):
# If no password is set (!= an empty password), the whole API will be available
# without authentication.
#password = "some password"

# A salt used to derive a cookie value from the password.
# If no password is set (default), a random value will be generated at each
# startup, invalidating the cookie sessions.
# If you enable this, you want to generate your own salt.
# Has to be 32 bytes in hex format.
# generate with python: secrets.token_hex(32)
#cookie_salt = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"

# If given, provide a spaceapi compatible output at /spaceapi
# SpaceAPI spec: https://spaceapi.io/docs/
#
# You can set any constant parts within the string.
# Please add an empty 'state' object to the root, clubstatusd will fill in
# 'open' and 'lastchanged'.
# clubstatusd will not validate the 'api' version field, so please update it
# yourself.
spaceapi = """
{
    "api": "0.13",
    "space": "Slopspace",
    "logo": "http://your-space.org/img/logo.png",
    "url": "http://your-space.org",
    "location": {
        "address": "Ulmer Strasse 255, 70327 Stuttgart, Germany",
        "lon": 9.236,
        "lat": 48.777
    },
    "contact": {
        "twitter": "@spaceapi"
    },
    "issue_report_channels": [
        "twitter"
    ],
    "state": {}
}
"""

[mqtt]
# MQTT Server to send changes to
# MQTT is enabled when uncommented
#server = "mqtt.example.org";
#port = 1883

# don't forget trailing slash
# default: no prefix
#topic_prefix = "status/"
